### ISSUE TITLE
Do you know about ScanCode for license detection?

### ISSUE THREAD

**Issue by pombredanne** [fabric8-analytics/fabric8-analytics-license-check#2]
See https://github.com/nexB/scancode-toolkit 
I am the maintainer... I will be happy to help if this works for you.

**Comment by bkabrda** [comment]
Hi @pombredanne, thanks for opening this issue. I haven't seen scancode-toolkit, but I'll definitely give it a closer look once things settle down a bit. I'll get in touch with you in case of any questions/issues.

**Comment by pombredanne** [comment]
@bkabrda sure thing. We are trying hard to make the very best license detection engine out there.

**Comment by pombredanne** [comment]
@bkabrda FWIW @richardfontana has played a bit with it too and may have an opinion on the topic.

**Comment by richardfontana** [comment]
@bkabrda I have been using ScanCode for some Red Hat-related work during the past few months. I have been impressed with how easy it is to use and also the responsiveness of the project to fixing issues.

**Comment by pombredanne** [comment]
@richardfontana thanks++ for the __very__ nice words!

**Comment by fridex** [comment]
Thanks to @jpopelka there is a PR that incorporates ScanCode for license detection - see https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/56

**Comment by fridex** [comment]
> Thanks to @jpopelka there is a PR that incorporates ScanCode for license detection - see fabric8-analytics/fabric8-analytics-worker#56

... so closing this issue. Thanks!
